### ISSUE TITLE
yml文件中的coversations如何训练使用

### ISSUE THREAD

**Issue by BobCN2017** [zqhZY/_rasa_chatbot#19]
如题，楼主chat_detection\data\chinese_dialogs目录下有很多yml文件，其中都语句对，请问这个文件夹下的数据如何加到bot中去。或者有什么链接介绍如何使用的，给一个也行。谢谢

**Comment by zqhZY** [comment]
目前的项目里没有加入这个逻辑，这里的数据是为了训练领域和闲聊分类，数据处理可以参考_rasa_chatbot/chat_detection/corpus.py  和_rasa_chatbot/chat_detection/data/baidu_konwn_questions.txt 
 构造闲聊类， 然后加入自己的领域数据做task类，参考 _rasa_chatbot/tools/trainsfer_raw_to_rasa.py 准换成json格式。

**Comment by BobCN2017** [comment]
好的，谢谢回复
