### ISSUE TITLE
同一句话，不同上下文，不同的intent， 怎么做？

### ISSUE THREAD

**Issue by red-frog** [zqhZY/_rasa_chatbot#32]
比如说， 是的

可能的对话：
bot：你肚子疼吗？
user：是的
bot：你有呕吐现象吗？
user：是的

那么这块两个是的是反映不同的情况，这个问题怎么解决呢？
我从AI研习社看到了您的分享，所以想请教下您这个问题，期待您的解答

**Comment by zqhZY** [comment]
一种简单的对话管理可以使用状态机的方式，在得到用户意图的时候根据自己的意图判断

**Comment by red-frog** [comment]
我通过formaction解决了这个问题，对于状态机，我得去了解下，谢谢了！
